"""Initial migration with full models

Revision ID: 78294d82a87b
Revises: 
Create Date: 2025-05-08 14:39:47.178783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '78294d82a87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('shared_data') # commented out to avoid dropping the table by Julie 11May 2025
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('meta_info')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('app_language', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('daily_goal_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receive_reminder', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('receive_email', sa.Boolean(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('receive_email')
        batch_op.drop_column('receive_reminder')
        batch_op.drop_column('daily_goal_minutes')
        batch_op.drop_column('app_language')
        batch_op.drop_column('streak_days')
        batch_op.drop_column('xp')
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_info', sqlite.JSON(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('extra_metadata')

    op.create_table('shared_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('permission', sa.VARCHAR(length=4), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
