"""Add is_active to user model

Revision ID: 9ba96a43be34
Revises: 854e247f6165
Create Date: 2025-05-11 16:12:38.721165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba96a43be34'
down_revision = '854e247f6165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
